### ISSUE TITLE
Task weight scripting

### ISSUE THREAD

**Issue by travissouthard** [stordahl/ctrl#3]
When adding tasks, instead of defaulting to zero, it may be more helpful for them to default to the remainder or to 1
If the default is the remainder, when adding multiple tasks, it may be helpful to use a script to set the default to automatically evenly weight the tasks.

For example, if the dice is set to 20, and there are 4 tasks and a 5th is added, the default would set it to a weight of 4 each (5 tasks with 4 weight = 20)

**Comment by stordahl** [comment]
Using Svelte's reactivity, this shouldn't be that hard to implement! Thanks for the idea
